name: Run Cypress Tests
on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - release
      - develop
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    container:
      image: cypress/browsers:22.15.0
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          browser: chrome